config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :bookings, only: [:index, :destroy] do
    member do
      patch :toggle_status
      patch :assign
      patch :cancel
    end
    resources :reviews, only: [:new, :create, :index, :edit, :update]
  end

  resources :mercenaries, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :my_mercenaries
    end
    resources :bookings, only: [:new, :create, :edit, :update]
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag "logo.png", alt: "Mercenaries Hub Logo", class: "img-fluid", style: "height: 40px;" %>
      <h3 class="navbar-main-title ms-2 mb-0">Mercenaries Hub</h3>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto text-light d-flex align-items-center gap-3">
        <% if user_signed_in? %>
          <div>
            <% if current_user.nickname.present? %>
              <span>Bienvenue <%= current_user.nickname %></span>
            <% else %>
              <span>Bienvenue <%= current_user.email %></span>
            <% end %>
          </div>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key,
                                 alt: "Avatar",
                                 width: 40,
                                 height: 40,
                                 crop: :thumb,
                                 gravity: :face,
                                 radius: :max,
                                 zoom: 1.3,
                                 class: "avatar" %>
              <% else %>
                <%= image_tag "default_avatar.jpg", class: "avatar", alt: "Default avatar" %>
              <% end %>
          </a>

            <div class="dropdown-menu dropdown-menu-end dropdown-menu-dark" aria-labelledby="navbarDropdown">
              <%= link_to "Tous les mercenaires", mercenaries_path, class: "dropdown-item" %>
              <hr>
              <%= link_to "Mes contrats", bookings_path, class: "dropdown-item" %>
              <%= link_to "Mes mercenaires", my_mercenaries_mercenaries_path, class: "dropdown-item" %>
              <%= link_to "Ajouter un mercenaire", new_mercenary_path, class: "dropdown-item" %>
              <hr>
              <%= link_to "Editer mon profil", edit_user_registration_path , class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>